### ISSUE TITLE
On Time Membership Expiration Date

### ISSUE THREAD

**Issue by jasonbails** [matthewstriks/CERMS#77]
Hey! This isn't the end of the world, but it would just help make it look cleaner. The expiration date on new one-time memberships is showing as a null message. Can we just make it blank or something? We are pretty much only concerned with the expiration date on the other types of memberships

![Screenshot 2023-12-22 144650](https://github.com/matthewstriks/CERMS/assets/141863738/5cb09117-48aa-4d9c-a3c2-73b5f0ecf2be)

**Comment by matthewstriks** [comment]
Weird bug... only occurs when products are edited. New update will fix this... for now just create new membership with correct information and do not edit
